### ISSUE TITLE
Duplicate accounts in anope_db_NickCore

### ISSUE THREAD

**Issue by Madriix** [anope/anope#511]
### Description

There are duplicate entries in `anope_db_NickCore` where the uniqueid is set to '0'

### Steps to reproduce the issue

I can't reproduce the issue. It affects a few accounts - around 1,100 out of 5,000

### Describe the results you received

Example : 

![Image](https://github.com/user-attachments/assets/77207297-e5c7-4b04-9289-30e5a968bb05)

everal others exist too, all with invalid uniqueids,  except one that has a valid uniqueid

### Anope version

2.1.14

**Comment by sadiepowell** [comment]
The duplicates are a long standing issue you've been having, right? I think that your database is broken (probably because of you force-killing Anope whilst its writing to the database) because we haven't had any other reports of this. You can try exporting to flatfile then re-importing and then only shutting down with `/msg OperServ SHUTDOWN` to see if that fixes it.

The unique identifier issue is a different issue which should be fixed in cac10aaa4163b5732068d90f03093ab43328a19a.

**Comment by Madriix** [comment]
@SadieCat How do I export to flatfile? I just tried disabling the db_sql (and db_sql_live) module, but that didn’t fix the flatfile.
./anope was restarted

**Comment by Madriix** [comment]
**Step 1:**  

I removed duplicates in `anope_db_NickCore`:

```
DELETE FROM anope_db_NickCore WHERE uniqueid=0
```
or
```
DELETE t1
FROM anope_db_NickCore t1
JOIN anope_db_NickCore t2 
  ON t1.display = t2.display 
  AND t1.id > t2.id;
```

Then I placed the `"sql_live"` module before `flatfile` and used `/msg OperServ SHUTDOWN`.

It seems fixed, but I can't confirm yet because we need to wait and see if people creating new accounts via `sql_authentication` no longer generate duplicates in `anope_db_NickCore`.

**Step 2:**  
I also copied all the changes made here for May 16: https://github.com/anope/anope/commits/2.1/  
It was a failure on my end; Anope starts fine and works, but it continues to create duplicates. Additionally, I can't delete `uniqueid=0` because they all have IDs, and the duplicates have multiplied. I reverted to Step 1, before the changes.
